#!/usr/bin/env bash 


if [[ $TERM = *rxvt* ]]; then
  file=$(mpc --format ~/mus/%file% current)
  printf '\e]20;;100x100+1000+1000\a'
  ffmpeg -y -i "$file" /tmp/cover.png -loglevel quiet
  printf '\e]20;%s;100x50+100+50:op=keep-aspect\a' /tmp/cover.png
  #notify-send "Now Playing ♫" "$(mpc current)"
fi
