#################################################################
#################################################################
#################################################################
#   In the name of Allah, the most Gracious, the most Merciful. #
#                                                               # 
#    ▓▓▓▓▓▓▓▓▓▓                                                 #
#   ░▓ Author ▓ Abdullah Khabir <https://abdullah.support>      #
#   ░▓▓▓▓▓▓▓▓▓▓ YouTube <https://YouTube.com/AbdullahToday>     #
#   ░░░░░░░░░░                                                  #
#                                                               # 
#   ░█▀█░█░░░█▀█░█▀▀░█▀▄░▀█▀░▀█▀░▀█▀░█░█                        #
#   ░█▀█░█░░░█▀█░█░░░█▀▄░░█░░░█░░░█░░░█░                        #
#   ░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░░▀░░░▀░                        #
#################################################################
#################################################################
#################################################################


[colors]
draw_bold_text_with_bright_colors = false


[general]
import = [
    "options.toml",
    "vesper.toml",
    "fonts.toml"
]
live_config_reload = true
