#################################################################
#################################################################
#################################################################
#   In the name of Allah, the most Gracious, the most Merciful. #
#                                                               # 
#    ▓▓▓▓▓▓▓▓▓▓                                                 #
#   ░▓ Author ▓ Abdullah Khabir <https://abdullah.support>      #
#   ░▓▓▓▓▓▓▓▓▓▓ YouTube <https://YouTube.com/AbdullahToday>     #
#   ░░░░░░░░░░                                                  #
#                                                               # 
#   ░█▀█░█░░░█▀█░█▀▀░█▀▄░▀█▀░▀█▀░▀█▀░█░█                        #
#   ░█▀█░█░░░█▀█░█░░░█▀▄░░█░░░█░░░█░░░█░                        #
#   ░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░░▀░░░▀░                        #
#################################################################
#################################################################
#################################################################

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.9
padding = { x = 10, y = 10 }
dynamic_padding = true
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
size = 14
#[font.normal]
# family = "VictorMono Nerd Font"
# family = "CaskaydiaCove Nerd Font"
# family = "Iosevka Nerd Font"
# normal = { family = "BlexMono Nerd Font", style = "Regular" }
# normal = { family = "Iosevka Nerd Font", style = "Regular" }
# normal = { family = "BlexMono Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# normal = { family = "IosevkaTermNerdFont", style = "Regular" }
# normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
#normal = { family = "VictorMono Nerd Font", style = "Regular" }
#bold = { family = "VictorMono Nerd Font", style = "Bold" }
#italic = { family = "VictorMono Nerd Font", style = "Italic" }
#bold_italic = { family = "VictorMono Nerd Font", style = "Bold Italic" }
normal = { family = "BlexMono Nerd Font", style = "Regular" }
bold = { family = "BlexMono Nerd Font", style = "Bold" }
italic = { family = "BlexMono Nerd Font", style = "Italic" }
bold_italic = { family = "BlexMono Nerd Font", style = "Bold Italic" }

#[font.normal]
#family = "VictorMono Nerd Font"
#style = "Regular"
#
#[font.bold]
#family = "VictorMono Nerd Font"
#style = "Bold"
#
#[font.italic]
#family = "VictorMono Nerd Font"
#style = "Italic"
#
#[font.bold_italic]
#family = "VictorMono Nerd Font"
#style = "Bold Italic"

[cursor]
style = "Underline"
unfocused_hollow = false

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
