#!/bin/sh     
coded_by='

In the name of Allah, the most Gracious, the most Merciful.

 ▓▓▓▓▓▓▓▓▓▓
░▓ Author ▓ Abdullah <https://abdullah.today>
░▓▓▓▓▓▓▓▓▓▓
░░░░░░░░░░

░█▀█░█▀▄░█▀▀░█▀▀░█▀▀░█░░░█▀▀░█▀▀░▀█▀░▀█▀░█▀█░█▀█░█▀▀
░█▀▀░█▀▄░█▀▀░▀▀█░█▀▀░█░░░█▀▀░█░░░░█░░░█░░█░█░█░█░▀▀█
░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀░░▀░░▀▀▀░▀▀▀░▀░▀░▀▀▀
'

bspc node -p \~$*
exit
bspc node -p $*
