#Section "InputClass"
#	Identifier "touchpad"
#	Driver	"libinput"
#	MatchIsTouchpad	"on"
#	Option	"Tapping" "on"
#	Option	"TappingButtonMap" "lmr"
#EndSection

Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lmr"
    # This prevents it from trying to open legacy mouse nodes
    # Option "Device" "/dev/input/event11"
EndSection
