#!/usr/sbin/nft -f
flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        iif "lo" accept
        ct state established,related accept
        ct state invalid drop

        icmp type echo-request accept
        icmpv6 type { echo-request, nd-neighbor-solicit, nd-neighbor-advert, nd-router-advert } accept

        # only keep this if you actually run sshd — see Tier 4
        tcp dport 22 ct state new limit rate 4/minute accept comment "ssh, rate-limited"
    }

    chain forward {
    type filter hook forward priority 0; policy drop;

    iifname "docker0" accept
    iifname "br-*" accept
    oifname "docker0" ct state established,related accept
    oifname "br-*" ct state established,related accept
    
    }
    
    chain output {
        type filter hook output priority 0; policy accept;
    }
}
