stream.rules = [
    {
        matches = [
            { application.name = "Google Chrome input" }
        ]
        actions = {
            update-props = {
                target.object = "echo_cancel_source"
            }
        }
    }
]
