context.modules = [
    {
        name = libpipewire-module-echo-cancel
        args = {
            library.name = aec/libspa-aec-webrtc
            monitor.mode = true

            aec.args = {
                webrtc.extended_filter = true
                webrtc.delay_agnostic = true
                webrtc.high_pass_filter = true
                webrtc.noise_suppression = true
                webrtc.voice_detection = false
                webrtc.gain_control = false
                webrtc.experimental_agc = false
                webrtc.experimental_ns = false
            }

            capture.props = {
                node.name = "echo_cancel_capture"
                node.description = "Echo Cancellation Capture"
                node.passive = true
                target.object = "alsa_input.pci-0000_00_1f.3.analog-stereo"
            }

            source.props = {
                node.name = "echo_cancel_source"
                node.description = "Echo Cancellation Microphone"
            }
        }
    }
]
