[redshift]
temp-day=5000
temp-night=4000
fade=1
gamma=0.8
location-provider=manual
adjustment-method=randr
transition=1

[manual]
lat=33.6844
lon=73.0479

[randr]
screen=0
crtc=0

[vidmode]
screen=0

[drm]
card=/dev/dri/card1
crtc=0
