name: ShellCheck Linting

on:
  push:
    branches: [ main ]

jobs:
  shellcheck:
    name: Scan Shell Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          # Only match files that end exactly with .sh
          file_regex: '.*\.sh$'
        env:
          SHELLCHECK_OPTS: -x
